categories = [
"AI 및 머신러닝", "SaaS", "메타버스 콘텐츠", "앱 개발 관련 콘텐츠", "블록체인 및 Web3",
"IT 하드웨어 및 디바이스", "전자상거래", "중고거래 및 리셀", "지역커뮤니티 및 네트워크", "리뷰 및 큐레이션 기반",
"로컬푸드", "해외음식", "간편식/밀키트", "헬스케어/다이어트", "디저트/간식", "소스/조미료", "주류", "음료/커피",
"e-스포츠 관련 제품", "캠핑", "홈트레이닝", "등산", "골프", "러닝", "낚시", "테니스", "자전거", "스포츠 레슨/트레이닝",
"오락 콘텐츠", "보드게임 및 TPRG", "온라인 게임", "디지털 게임", "웹툰 및 스토리 컨텐츠", "대중 공연", "음악",
"영상", "HR 솔루션", "노무 관리", "리걸 테크", "컨설팅", "리모트 워크", "홍보&마케팅",
"고기술", "중고기술", "중저기술", "저기술",
"네트워크 및 통신 기술", "데이터 분석 및 처리", "정보 보안 및 사이버 보안", "레저 및 관광", "뷰티 및 웰니스",
"홈&리빙(가구, 인테리어, 주방용품)", "패션 및 의류", "반려동물", "숙박 및 임대업", "생명과학 및 바이오테크",
"에너지 및 환경 기술", "R&D 및 실험 서비스", "ESG", "산업디자인", "미술 및 공예", "출판 및 문학",
"공연 예술 및 전시회", "문화유산", "차량 공유", "전기차 관련 기술", "드론", "디지털 금융 및 지급 결제",
"재무관리", "인슈어테크"
]
categories_en = [
    "AI and Machine Learning",
    "SaaS",
    "Metaverse Content",
    "App Development Content",
    "Blockchain and Web3",
    "IT Hardware and Devices",
    "E-Commerce",
    "Secondhand Trade and Resale",
    "Regional Communities and Networks",
    "Review and Curation-Based Platforms",
    "Local Food",
    "International Cuisine",
    "Ready-to-Cook/Meal Kits",
    "Healthcare/Diet Products",
    "Desserts/Snacks",
    "Sauces/Seasonings",
    "Alcoholic Beverages",
    "Beverages/Coffee",
    "E-Sports-Related Products",
    "Camping",
    "Home Training",
    "Hiking",
    "Golf",
    "Running",
    "Fishing",
    "Tennis",
    "Cycling",
    "Sports Lessons/Training",
    "Entertainment Content",
    "Board Games and TPRG",
    "Online Games",
    "Digital Games",
    "Webtoons and Story Content",
    "Live Performances",
    "Music",
    "Video/Film",
    "HR Solutions",
    "Labor Management",
    "Legal Tech",
    "Consulting",
    "Remote Work Solutions",
    "Public Relations and Marketing",
    "High Technology (Semiconductors, Aerospace)",
    "Medium-High Technology (Automotive, Industrial Machinery)",
    "Medium-Low Technology (General Machinery, Consumer Goods)",
    "Low Technology (Traditional Crafts, Small-Scale Production)",
    "Networking and Communication Technology",
    "Data Analysis and Processing",
    "Information and Cybersecurity",
    "Leisure and Tourism",
    "Beauty and Wellness",
    "Home and Living (Furniture, Interior Design, Kitchenware)",
    "Fashion and Apparel",
    "Pet Care",
    "Accommodation and Rentals",
    "Life Sciences and Biotechnology",
    "Energy and Environmental Technology",
    "R&D and Laboratory Services",
    "ESG (Environmental, Social, and Governance)",
    "Industrial Design",
    "Art and Craft",
    "Publishing and Literature",
    "Performing Arts and Exhibitions",
    "Cultural Heritage",
    "Car Sharing",
    "Electric Vehicle-Related Technology",
    "Drones",
    "Digital Finance and Payment Systems",
    "Financial Management",
    "InsurTech"
]

category_dicts = [{"id": i + 1, "name": category} for i, category in enumerate(categories)]
